/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QuestionnaireUserAllOf struct for QuestionnaireUserAllOf
type QuestionnaireUserAllOf struct {
	Targets        []string `json:"targets"`
	Administrators []string `json:"administrators"`
}
