/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// NewQuestionnaire struct for NewQuestionnaire
type NewQuestionnaire struct {
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	ResTimeLimit time.Time `json:"res_time_limit"`
	// アンケートの結果を, 運営は見られる (\"administrators\"), 回答済みの人は見られる (\"respondents\") 誰でも見られる (\"public\")
	ResSharedTo    string   `json:"res_shared_to"`
	Targets        []string `json:"targets"`
	Administrators []string `json:"administrators"`
}
