/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ResponseAllOf struct for ResponseAllOf
type ResponseAllOf struct {
	SubmittedAt time.Time `json:"submitted_at"`
	ModifiedAt  time.Time `json:"modified_at"`
}
