/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QuestionnaireByIdAllOf struct for QuestionnaireByIdAllOf
type QuestionnaireByIdAllOf struct {
	Respondents []string `json:"respondents"`
}
