/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Response struct for Response
type Response struct {
	QuestionnaireID int32          `json:"questionnaireID"`
	Body            []ResponseBody `json:"body"`
	SubmittedAt     time.Time      `json:"submitted_at"`
	ModifiedAt      time.Time      `json:"modified_at"`
}
