/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// QuestionDetailsAllOf struct for QuestionDetailsAllOf
type QuestionDetailsAllOf struct {
	CreatedAt time.Time `json:"created_at"`
}
