/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Group struct for Group
type Group struct {
	GroupId     string     `json:"groupId"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	AdminUser   string     `json:"adminUser"`
	Members     [][]string `json:"members"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}
