/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ResponseSummary struct for ResponseSummary
type ResponseSummary struct {
	ResponseID         int32     `json:"responseID"`
	QuestionnaireID    int32     `json:"questionnaireID"`
	QuestionnaireTitle string    `json:"questionnaire_title"`
	ResTimeLimit       time.Time `json:"res_time_limit"`
	SubmittedAt        time.Time `json:"submitted_at"`
	ModifiedAt         string    `json:"modified_at"`
}
