/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ResponseDetailsAllOf struct for ResponseDetailsAllOf
type ResponseDetailsAllOf struct {
	ResponseID int32 `json:"responseID"`
}
