/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QuestionnaireMyAdministratesAllOf struct for QuestionnaireMyAdministratesAllOf
type QuestionnaireMyAdministratesAllOf struct {
	// 回答必須でない場合、またはすべてのターゲットが回答済みの場合、true を返す。それ以外はfalseを返す。
	AllResponded bool     `json:"all_responded"`
	Respondents  []string `json:"respondents"`
}
