/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// QuestionnaireMyTargetedAllOf struct for QuestionnaireMyTargetedAllOf
type QuestionnaireMyTargetedAllOf struct {
	RespondedAt time.Time `json:"responded_at"`
}
