/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// QuestionnaireForList struct for QuestionnaireForList
type QuestionnaireForList struct {
	QuestionnaireID int32     `json:"questionnaireID"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	ResTimeLimit    time.Time `json:"res_time_limit"`
	CreatedAt       time.Time `json:"created_at"`
	ModifiedAt      time.Time `json:"modified_at"`
	// アンケートの結果を, 運営は見られる (\"administrators\"), 回答済みの人は見られる (\"respondents\") 誰でも見られる (\"public\")
	ResSharedTo string `json:"res_shared_to"`
	// 自分がターゲットになっているかどうか
	IsTargeted bool `json:"is_targeted"`
}
