/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ResponseBody struct for ResponseBody
type ResponseBody struct {
	QuestionID     int32    `json:"questionID"`
	QuestionType   string   `json:"question_type"`
	Response       string   `json:"response"`
	OptionResponse []string `json:"option_response"`
}
