/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QuestionnaireForListAllOf struct for QuestionnaireForListAllOf
type QuestionnaireForListAllOf struct {
	// 自分がターゲットになっているかどうか
	IsTargeted bool `json:"is_targeted"`
}
