/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// User struct for User
type User struct {
	UserId      string `json:"userId"`
	TraqID      string `json:"traqID"`
	DisplayName string `json:"displayName"`
	IconFileId  string `json:"iconFileId"`
	TwitterId   string `json:"twitterId"`
}
