/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QuestionAllOf struct for QuestionAllOf
type QuestionAllOf struct {
	QuestionID int32 `json:"questionID"`
}
