/*
 * anke-to API
 *
 * anke-to API
 *
 * API version: 1.0.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// NewResponse struct for NewResponse
type NewResponse struct {
	QuestionnaireID int32          `json:"questionnaireID"`
	Body            []ResponseBody `json:"body"`
}
