version: "2"
linters:
  enable:
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - tuning/openapi
      - model/mock_model
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008 # ignore embedded field check
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - tuning/openapi
      - model/mock_model
