// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/traPtitech/anke-to/model"
	"github.com/traPtitech/anke-to/router"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InjectAPIServer() *router.API {
	administrator := model.NewAdministrator()
	respondent := model.NewRespondent()
	question := model.NewQuestion()
	middleware := router.NewMiddleware(administrator, respondent, question)
	questionnaire := model.NewQuestionnaire()
	target := model.NewTarget()
	option := model.NewOption()
	scaleLabel := model.NewScaleLabel()
	validation := model.NewValidation()
	routerQuestionnaire := router.NewQuestionnaire(questionnaire, target, administrator, question, option, scaleLabel, validation)
	routerQuestion := router.NewQuestion(validation, question, option, scaleLabel)
	response := model.NewResponse()
	routerResponse := router.NewResponse(questionnaire, validation, scaleLabel, respondent, response)
	result := router.NewResult(respondent, questionnaire, administrator)
	user := router.NewUser(respondent, questionnaire, target, administrator)
	api := router.NewAPI(middleware, routerQuestionnaire, routerQuestion, routerResponse, result, user)
	return api
}

// wire.go:

var (
	administratorRepository = wire.Bind(new(model.AdministratorRepository), new(*model.Administrator))
	optionRepository        = wire.Bind(new(model.OptionRepository), new(*model.Option))
	questionnaireRepository = wire.Bind(new(model.QuestionnaireRepository), new(*model.Questionnaire))
	questionRepository      = wire.Bind(new(model.QuestionRepository), new(*model.Question))
	respondentRepository    = wire.Bind(new(model.RespondentRepository), new(*model.Respondent))
	responseRepository      = wire.Bind(new(model.ResponseRepository), new(*model.Response))
	scaleLabelRepository    = wire.Bind(new(model.ScaleLabelRepository), new(*model.ScaleLabel))
	targetRepository        = wire.Bind(new(model.TargetRepository), new(*model.Target))
	validationRepository    = wire.Bind(new(model.ValidationRepository), new(*model.Validation))
)
