// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/traPtitech/anke-to/controller"
	"github.com/traPtitech/anke-to/handler"
	"github.com/traPtitech/anke-to/model"
	"github.com/traPtitech/anke-to/traq"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InjectAPIServer() *handler.Handler {
	questionnaire := model.NewQuestionnaire()
	target := model.NewTarget()
	administrator := model.NewAdministrator()
	question := model.NewQuestion()
	option := model.NewOption()
	scaleLabel := model.NewScaleLabel()
	validation := model.NewValidation()
	transaction := model.NewTransaction()
	webhook := traq.NewWebhook()
	controllerQuestionnaire := controller.NewQuestionnaire(questionnaire, target, administrator, question, option, scaleLabel, validation, transaction, webhook)
	respondent := model.NewRespondent()
	response := model.NewResponse()
	controllerResponse := controller.NewResponse(questionnaire, respondent, response, target, question, validation, scaleLabel)
	middleware := controller.NewMiddleware(administrator, respondent, question, questionnaire)
	handlerHandler := handler.NewHandler(controllerQuestionnaire, controllerResponse, middleware)
	return handlerHandler
}

// wire.go:

var (
	administratorBind = wire.Bind(new(model.IAdministrator), new(*model.Administrator))
	optionBind        = wire.Bind(new(model.IOption), new(*model.Option))
	questionnaireBind = wire.Bind(new(model.IQuestionnaire), new(*model.Questionnaire))
	questionBind      = wire.Bind(new(model.IQuestion), new(*model.Question))
	respondentBind    = wire.Bind(new(model.IRespondent), new(*model.Respondent))
	responseBind      = wire.Bind(new(model.IResponse), new(*model.Response))
	scaleLabelBind    = wire.Bind(new(model.IScaleLabel), new(*model.ScaleLabel))
	targetBind        = wire.Bind(new(model.ITarget), new(*model.Target))
	validationBind    = wire.Bind(new(model.IValidation), new(*model.Validation))
	transactionBind   = wire.Bind(new(model.ITransaction), new(*model.Transaction))

	webhookBind = wire.Bind(new(traq.IWebhook), new(*traq.Webhook))
)
