package router

import (
	"testing"

	"github.com/go-playground/validator/v10"
	"github.com/stretchr/testify/assert"
)

func TestPostQuestionValidate(t *testing.T) {
	t.Parallel()

	tests := []struct {
		description string
		request     *PostQuestionRequest
		isErr       bool
	}{
		{
			description: "旧クライアントの一般的なTextタイプの質問なのでエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "questionnaireIDが0でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 0,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "questionNumが0でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     0,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "questionNumが負なのでエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     -1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "pageNumが0でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         0,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "pageNumが負なのでエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         -1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "質問文が空なのでエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "isRequiredがfalseでもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      false,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "Textタイプでoptionがnullでもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         nil,
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "Textタイプでoptionが50文字以上でもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"012345678901234567890123456789012345678901234567890"},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "TextタイプでscaleLabelRightがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "TextタイプでscaleLabelLeftがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "TextタイプでscaleLabelRightが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "012345678901234567890123456789012345678901234567890",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "TextタイプでscaleLabelLeftが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "012345678901234567890123456789012345678901234567890",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "TextタイプでscaleMinが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        0,
			},
		},
		{
			description: "TextタイプでscaleMaxが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        -1,
			},
		},
		{
			description: "TextタイプでscaleMaxが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        1,
			},
		},
		{
			description: "TextタイプでscaleMinが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        1,
			},
		},
		{
			description: "TextタイプでscaleMinがscaleMaxより大きいときエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "regexPatternが指定されていてもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
				RegexPattern:    ".*",
			},
		},
		{
			description: "MinBoundが設定されていてもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
				MinBound:        "0",
			},
		},
		{
			description: "MinBoundが数字でない時エラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
				MinBound:        "a",
			},
			isErr: true,
		},
		{
			description: "MaxBoundが設定されていてもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
				MaxBound:        "0",
			},
		},
		{
			description: "MaxBoundが数字でない時エラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
				MaxBound:        "a",
			},
			isErr: true,
		},
		{
			description: "旧クライアントの一般的なTextAreaタイプの質問なのでエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "TextAreaタイプでoptionがnullでもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         nil,
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "TextAreaタイプでoptionが50文字以上でもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"012345678901234567890123456789012345678901234567890"},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "TextAreaタイプでscaleLabelRightがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "TextAreaタイプでscaleLabelLeftがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "TextAreaタイプでscaleLabelRightが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "012345678901234567890123456789012345678901234567890",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "TextAreaタイプでscaleLabelLeftが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "012345678901234567890123456789012345678901234567890",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "TextAreaタイプでscaleMinが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        0,
			},
		},
		{
			description: "TextAreaタイプでscaleMaxが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        -1,
			},
		},
		{
			description: "TextAreaタイプでscaleMaxが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        1,
			},
		},
		{
			description: "TextAreaタイプでscaleMinが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        1,
			},
		},
		{
			description: "TextAreaタイプでscaleMinがscaleMaxより大きいときエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "TextArea",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "旧クライアントの一般的なNumberタイプの質問なのでエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "Numberタイプでoptionがnullでもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         nil,
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "Numberタイプでoptionが50文字以上でもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"012345678901234567890123456789012345678901234567890"},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "NumberタイプでscaleLabelRightがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "NumberタイプでscaleLabelLeftがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "NumberタイプでscaleLabelRightが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "012345678901234567890123456789012345678901234567890",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "NumberタイプでscaleLabelLeftが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "012345678901234567890123456789012345678901234567890",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "NumberタイプでscaleMinが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        0,
			},
		},
		{
			description: "NumberタイプでscaleMaxが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        -1,
			},
		},
		{
			description: "NumberタイプでscaleMaxが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        1,
			},
		},
		{
			description: "NumberタイプでscaleMinが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        1,
			},
		},
		{
			description: "NumberタイプでscaleMinがscaleMaxより大きいときエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Number",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "旧クライアントの一般的なCheckboxタイプの質問なのでエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"a", "b"},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "Checkboxタイプでoptionがnullでエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         nil,
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "Checkboxタイプでoptionが50文字以上でエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"012345678901234567890123456789012345678901234567890"},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "CheckboxタイプでscaleLabelRightがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "CheckboxタイプでscaleLabelLeftがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "CheckboxタイプでscaleLabelRightが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "012345678901234567890123456789012345678901234567890",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "CheckboxタイプでscaleLabelLeftが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "012345678901234567890123456789012345678901234567890",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "CheckboxタイプでscaleMinが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        0,
			},
		},
		{
			description: "CheckboxタイプでscaleMaxが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        -1,
			},
		},
		{
			description: "CheckboxタイプでscaleMaxが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        1,
			},
		},
		{
			description: "CheckboxタイプでscaleMinが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        1,
			},
		},
		{
			description: "CheckboxタイプでscaleMinがscaleMaxより大きいときエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Checkbox",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "旧クライアントの一般的なMultipleChoiceタイプの質問なのでエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"a", "b"},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "MultipleChoiceタイプでoptionがnullでエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         nil,
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "MultipleChoiceタイプでoptionが50文字以上でエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"012345678901234567890123456789012345678901234567890"},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "MultipleChoiceタイプでscaleLabelRightがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "MultipleChoiceタイプでscaleLabelLeftがあってもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "MultipleChoiceタイプでscaleLabelRightが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "012345678901234567890123456789012345678901234567890",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "MultipleChoiceタイプでscaleLabelLeftが50字を超えてもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "012345678901234567890123456789012345678901234567890",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "MultipleChoiceタイプでscaleMinが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        0,
			},
		},
		{
			description: "MultipleChoiceタイプでscaleMaxが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        -1,
				ScaleMax:        -1,
			},
		},
		{
			description: "MultipleChoiceタイプでscaleMaxが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        1,
			},
		},
		{
			description: "MultipleChoiceタイプでscaleMinが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        1,
			},
		},
		{
			description: "MultipleChoiceタイプでscaleMinがscaleMaxより大きいときエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "MultipleChoice",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        1,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "旧クライアントの一般的なLinearScaleタイプの質問なのでエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        1,
				ScaleMax:        5,
			},
		},
		{
			description: "LinearScaleタイプでoptionがnullでもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         nil,
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
		},
		{
			description: "LinearScaleタイプでoptionが50文字以上でもエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{"012345678901234567890123456789012345678901234567890"},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "LinearScaleタイプでscaleLabelRightがなくてもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: false,
		},
		{
			description: "LinearScaleタイプでscaleLabelLeftがなくてもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: false,
		},
		{
			description: "LinearScaleタイプでscaleLabelLeft＆Rightがなくてもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "",
				ScaleLabelLeft:  "",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: false,
		},
		{
			description: "LinearScaleタイプでscaleLabelRightが50字を超えていたらエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "012345678901234567890123456789012345678901234567890",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "LinearScaleタイプでscaleLabelLeftが50字を超えていたらエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "LinearScale",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "012345678901234567890123456789012345678901234567890",
				ScaleMin:        0,
				ScaleMax:        0,
			},
			isErr: true,
		},
		{
			description: "LinearScaleタイプでscaleMinが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        -1,
				ScaleMax:        0,
			},
		},
		{
			description: "LinearScaleタイプでscaleMaxが負でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        -1,
				ScaleMax:        -1,
			},
		},
		{
			description: "LinearScaleタイプでscaleMaxが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        0,
				ScaleMax:        1,
			},
		},
		{
			description: "LinearScaleタイプでscaleMinが正でもエラーなし",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        1,
				ScaleMax:        1,
			},
		},
		{
			description: "LinearScaleタイプでscaleMinがscaleMaxより大きいときエラー",
			request: &PostQuestionRequest{
				QuestionnaireID: 1,
				QuestionType:    "Text",
				QuestionNum:     1,
				PageNum:         1,
				Body:            "発表タイトル",
				IsRequired:      true,
				Options:         []string{},
				ScaleLabelRight: "右",
				ScaleLabelLeft:  "左",
				ScaleMin:        1,
				ScaleMax:        0,
			},
			isErr: true,
		},
	}

	for _, test := range tests {
		validate := validator.New()

		t.Run(test.description, func(t *testing.T) {
			err := validate.Struct(test.request)

			if test.isErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}
