// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9XXPUxpr/V3Hp/7+A2jFjXs7Fzp2JU6dcFXIght2L4HLJnsZWdkYaJA3golxlaQIY",
	"PIAXAo4xwTg4xuAwJocsx4CB77JtjcdXfIWtbr11t1qjljzjkFOnKpXCUr887/300z/1XJbGtHJFU4Fq",
	"GlLhslSRdbkMTKDjvyZk48TkgC6fMwfVU1WgT6KHRWCM6UrFVDRVKkimXgXQajiPf3fmZuC01br23Jm5",
	"ip4sPtp58QO0Gtubs83FTWjdhFbdefGj83ANWgvQnoX2z7D2Ctq/wdoWrM1AqwGtj9C+49y+73yY99pM",
	"22fVc3LJyDDHPLSeQ+t74WmYfsFsqIn1BlqrqCszGGcYKScpSDDnsbxykiqXgVQgRCnlJGNsApRlJExz",
	"soLejmpaCciqNDWVc1t+A4yKphogq9w/bc2EMrHv7C6sQOv2p63r3dKBwHyfoT58KSepRDHSOQFhjiyJ",
	"+cBmuWxH5EwM9RRaG1wZJozJFyQaK1aQ/oj0WLHC9OSTJEZVM/92AegD1XizdudtPlzaXZiDVn3XugXR",
	"f6uIaY91G/OJWHVp6zmAxH8w19OuLzJ13NG2nbl1aFv4uce/Pw4W/kE4bcPaNVi7B+1nsLaObXTD1Usb",
	"ewp5S5KCppYm+4tlRVUMU5dNUDw+eSJeIL6f1XcayztzV1vTV6C1jkXxRFAssR27LhMupyLiEYh/0TUg",
	"yjnTZvvdL87K/a5yKx5SUOvTsj4OTEUdF9E/tD8i37T/Dms1TFGMMnmCEO3bTdEQzCbJpiKPxwtk+/09",
	"WHuA2dncWWxAa7bnQPPhc6fxYOfDszByWhuHyWYHYyhDU/HIUVQTjAMdk3O+Cgw0uSorOhgcGFRPyuZE",
	"lDAmhA4OhOKooA7BnMx4Uk7SwfmqooOiVEAKS0eOER9LvdA9D60laH3frF1xHv/GXTSxPp8gfSJDeY7f",
	"vvTWD2sJG0QD1v4b1p7B2jKW6Uc4bbdWrjXvvWzWrzmNB87tjVbtvW8D4FKlpBWBVMCWwZc8ywalBcUE",
	"ZYPHf85/Iuu6PInlofuhIlYzrvvHKyQcIa0u/J5Dmh6fHWxvrkLr1e7jqz0Htt8/bM7MNed/aS7Y0Ko3",
	"77/E6vm+56xkVEfLimmC4ohsnpVyPUxT5/aK266XbXhal88PDkCr0fzxGprkrGTq8nmlSL3bXbjpvusN",
	"XzYXf2/ef8klpqwVlXNKMAXTMqSFatcT52SGptO5wf/XwTmpIP2/fLj5yLtvjfw3hEhPI4kjORtA1scm",
	"YiWM7NFeQbZcW0eCWHm48/vPccTgoXg+b5i6oo678+1dn2M6kAW0STdjGQk0qpglwGlAqNVv8XlqldDm",
	"lN8HO/iXRcU8RYYC9FAulf52Tip8237MU0wcncqlaH9cNkBijwhx7iJm9KtFnNcYeISKrlWAbioAM+TH",
	"NYOKYyJ0xUQ3Pxx9Sww9PDU8lZOSySuw1MnoeRJBZwygo0H+qmvVioHJwgOn7Rfyo41+B8ZMyaM5yJEo",
	"VdOE+pF1RCmiP8EluVwpAalwOMeLw+w07en8GlwMSMCC9AgmFUa7PG7Qc+aMt4ac0/SybEoFqVpVilKO",
	"DSCsGnPS1+BioOXU9i1kqn7jIWCiJMs4Pum62zA9+15cLBUd3XMXUpZpPYbUfMQ3RrXiZBoq/JGOo35T",
	"OamsqINu18NRC1CMkSLeI5PG7GYYnAyY5CHomXMpHOZ4FUtNG8fyReI5FjepiQoQtR7m+ZmmAgE7Iok7",
	"DS4luyjb4SsNO5Z4p6+r5VGcMIp3GVLU8RL4YkJTxkCqjieqJVOpZOo6NCaXsJci6/yDQkTEJ8OchLMf",
	"ffXcuXcb2ndaH987Nx5D6wPeXWzs/GNtd/Gqu2cItmBqtVQK9wSe0UtH+o709fYd7u07fLqvr4D/+7e+",
	"fy/09ZGRtSiboNdUyoAXXhkbTqAwmSTeokJpBMs3EjCoeS9HyVSMkdCX+JsS5+OV3ccz0JqF1jNoXYWW",
	"W2RjQ0LOzQD5ySrpr26zHDUXTQgvfMRYRkHUvdn+Qi7O6yTk5mxHQVdnu6Vyd7ZzSpePzO27fVT2zMip",
	"QwHSHIc62nK1SnTNjZhv/HqWk6qqcr4KvNdoGWMN0Z8ham48pj0VZmKWUD/NZFm+NHJBLlUBv5BQVtT4",
	"11NCZLtqzES1ZwFcokvyKCjxVZLMUpvOCQyT6gvbkpOKKZNyrGzCYV0zg/V212BxhMvEWxAbOXoH6rhb",
	"v8pmjkEEzUxYEH87RxwnHhVic1LTW3aAWi0jpTAdh3MJyx89ULuljogc4uR4HTpMRhBFBKlw23eaCMZp",
	"RWkhu3WYJN/HBEnBzbtAgu9RKcjAXTpISrj9zrZzP42zwlRb9wEigUzV0d/dDFTBgGyC0yiFzzTAfyjg",
	"ojxaAscn0/UfNPpVTZ0sa1UjbceBaqWkjMkm6FeNi0DvL5W0i6CYdpST1dGSYkygjsOsEr9wt1b9HMOm",
	"d12d2y4xVkdMk2hyA/QGp+3uJyR459dfDzuLj/BR0StYm4O1rd3Fq9tbDzCEoQHt69C++78/XoXWP6B9",
	"E1pPdxbetpbXgoOq7bdvoX3HmV3CG8p5vMVc6BHqZtnQWkEd7DqsbX3ashLFQXIhIA9TVkqfU4U6xrhS",
	"dTvhlfvT9hOo7slBGZre/BKYhMb25nRr9Smctj9tzTjXbzqLj5yND63fltFb+45fV0BKbi7YO/YbaD1t",
	"PX3SfDTnad5+iQ+it2Bt3j/iXHeW3kLrF4yOWHWPXqB1DxkFam9Dq/Fp67p7GihS68OnaEVeXbeTxX7/",
	"NLHoY/F49QJGZE79ozN3M4BAcKsce2TRLf3zCAq09GfWYWzBmFZHKIecb9TD0eg+OBCfKOAGYqcZPIKC",
	"7olBalA9p+1fnrDn5X6fg9agQQJRppKlSWQTEd0qxohMvmUchHJOpsKX+gwgnEiA5phEhsdA0W86IuO2",
	"I3LYmD33nsZrbN0FfiAn93h7ilGfs3tnMpYYAZ7DtIvHZoV82xa4A626c+XX3fuzfrjxMVJ75i6kQYCd",
	"b0BZUYtfqigF5rOk4xYjIGzCh46tOxsfPDBP7TmsPcIAglewdh1a9ebD686NNyRrGOG1ikE+r9H/rToR",
	"6J+iDMu+gduv+NqfJ4GIBEz3LlqRplegVXfxsW7nOrReRunYnba2Py57Eg+Ru8kyZYQgIFjS/3liNf33",
	"I2WwJzzenu2FoiSRs68Ug7OrqMjjYKQsX+KEp7mZ1hrGX/s4uea9l4nnIgz+LH3ig7sNVctlWZ9MXI4D",
	"6iPTJoqDWCAiQiEALl3da5HzJBLMW0kLsbCIYhWMIEJGTIVnphQWetp2ndGD+th3fGj0ErSvUzEcWfBt",
	"9H/sgjiLJLJKGmD9HHl+xw/3pkTFRJQH4qV0wWs0MjopgDsbmpB1EGDOSEVyB0zUqG/l+7Nf/FeR5w8q",
	"8uwh/dz/RJnZn5dKI/42h5cZEV+IEFlA3QsEmzPQ+hgEiB60rPXgc/cfUEcUdX6Cdt2D3VsbPRgNTLXo",
	"OUANG/OhCjPyQZHVFH9HNVKeDFE3bDLL/ypNajOUTkCHeOFWZCiUyZOfRIyMTrbPM9p9vkFkGNzJAtWG",
	"S0U4X4b1jBJpVCyx3OUYQ+NsnT8/6CIFq3AH8fb+yZH/tI/WoFkIQByRYqlXIKVrnF4JlN6eJCrJnYRH",
	"IrXEJW+DGjv/M9d89BDad3I9u9asc/81tDZaq7OYSpSl9xw46xVDzkrh91d+VMB7xUh7oqhyVjrY03r+",
	"EqUeth0ZV53UVHBW8pzdO1zxSi9sbcZtjHgOBes946CH+PDTtOvyHrCDLHCQgxWkygqJoS4FuDDXveSX",
	"1Ip4OS4F0DdHfSTR1cydpIqZlpZgTgCfOUwY3b/gmX9aeCb54rhsgEFPKdGVCieWAurzGsbEamqyOKxC",
	"ZC7Vk2z2qYZcl0ieKsZ3BKfaF6BbSHPnkEKx/LFG0iFUm6ixEmYSIaUjSLU0hPjOEaWk8+iwNHR5xh0h",
	"qwOArk6R0SEI117JCT7ZimSK/uK488MatBqGppsoWVxr7C4/InI1ZtHsbbuI9tJ/uh8poufevyJgmpx0",
	"qRfN1HtB1lW5jLz9W2nIn6Lf7B/6QsqRDwa+xE/C7XA/87fXwM1M+ol/4xekZP5TMSciR24oYPCKrHVo",
	"/RhNrb1c2T3rtO9gjMOa++V1sDnGmW/bw0TvpE88dUUdiJzLSJ2yciu2sWG+E+MTo3HlnnqKeO1x5o53",
	"Al8VcNqitOI6BbTfh9so1jMICE6O/AJUygX4/V7/H23cRMwngrKRa9LBn765o3n6w3+KuQnyBuQcX0zI",
	"qurCjZlzlCJVYoj7Ts79lJSzJldkCmsak2ngQfEYvGSDIFDcEEmuOPaAXuMaQadZTs0Z55vFJL5cwmO4",
	"Gizy7rWRT/V43zyGW62xypE+HmdolCFTLv/xssFUpJONS3iMbM4YvNQ7JVNc0SZuRJOZxaWrVLxidjis",
	"BiN9HsgjpiYXkf948Lzd+GElsOqzl1gIjGjB7Zrzp4yqAt8S5a1GY5pqymM4m/Q+lTd1+STaWeglqSBN",
	"mGbFKOTz44o5UR09NKaV8+i9qZhgbCIvq/8Fek28StNa8F709J8cDNYJ9ukFoBtu68OH+g719WqycRSN",
	"pFWAKlcUqSAdRc8lN75iWeSjx7leuZStl9+C1oxXorOWmj8tb797De07zbfTGH65cKRv+93r7Xe/bG/O",
	"cu4YsRqw9hzab+hLujxsJ5y2JUykLqPZUCSS/groT9sNTHR4OV1MVhw2yZN3OMTlw2Rz6ooJgQ7kLTUC",
	"zWMu/BHsGXthlED/6LVbAp2YK88EenDvrRPtR082zKSoR/r6fMfyaotyxT3EUzQ1/53hIpDFbqKIYiaw",
	"89LW3nzxxNnchNa6b6nu6fgHD644bUfte/fKTWdm3j+kIix7Kicdc+lv71H+9TzO+5+drdvQqu/ce4mP",
	"4m+4Y6GB/sIbKHqfTzz5i9C+i/9EfLgjHo2OOHTqK0RIY6m1XG8u2Lv370KrftRAzL2+goi2lnycj729",
	"+Q5a680XT1qrt1vLazu3P0Cr7txachYfY+7xEcy4EcEy4hyyohmcWBPcWRLlzAeCtokcJzWDuVHEjeXA",
	"MP3ia0cMKXKrwhS9auDSUcSQD3fHkD1kejtTjhcma9wRtC3b8XMy8QgTjIm3sb+pHLv85S8z11JNubSU",
	"gAlEqHKu38BXX7YxzwE8GGug6ZY2/o1kcWFT2B586ll7iNVvNAoODiCtfr+MQYVP06jUavjT1zMpM8fP",
	"W6LTBEWXDFlIlzX1h8SFuCVur1o/1ndMCGsbgj48fXdjoWu/Csnm2EQ601m53lz8nTQddz/EvV1v96dH",
	"3lt2wHV/HPemvbvQWuOY/7SNj73zLggBWnUWlxdARPLkVxc0jd5IEQuP3r/VSRPv/KobpVdo2U0ZCD3R",
	"dd4l/hL3mUA3LCfWkdKw3tnlNF+edIHtQ6ZsVuO3mxmx65mC+gmapD9biGc/FfgnifW0ultrL5zGg25H",
	"/OxWF1kPkgNtF82u82E32eL2EoG7F2/33yy7HD8pqQpmvM6VNQ/Dy97qzuYv0XruNwGkC8n32dvm/WvO",
	"i3lnZt6Do/pbN5FAGx4LdsjYk4tLvAt6BUtumYpZbNmsm6tAKM5/jpAfWGeHYnz72lIwW7SkFOUi+OJx",
	"58UP3lXXiArqg7dd65Zz6x1xI33d39C6dRThehVxhfznvCRQt6jub+mLnjfO8FkFJ5S5gvbdrG7tyWuO",
	"HTki/IsZS+7F7fTXXcL7gsCE91hdCywA5/1JK1fwew3UdyfB7zukPkA6MZl9xcm4cMRdzv+5Lh18SE2W",
	"9STQU7uDEK7VcX7Kg6NqAQsMPkRhje9yeMN/24JumB/RddyYIm7mQB35yYKUpdsInZQyRANWIG4/cvED",
	"1lEBOaGtUnPtmRuC/G/EiaqTcOQLbSCIaPhugXokosXFSG6JRSRGcqTZNliGSsxspTE16zZpOi/Mdd8M",
	"93HRTputElrg5ajtjHf3/t9bq0+zG2+CJXY+x6UsJ6aEEdqOWEmi08bTnYpvukRTLHTyag77GTqJAm6c",
	"9f0p4ub+hUu0qJu6fD4/RqA6uRHU1OVTOI+wYO0JLtXchLV1D7wmGlcp/GgXAyM1TyYwCs1mlhwsTlJZ",
	"whRSEamtEKfXVlfEHWAZFOXB/LqspuDz4CyIoZC/TBriyacT6jECsGx79bzBN968yqYeD5HbZfV4s2RT",
	"T8hfNvVw5NMJ9QSo1faBLryxKYN2znjw1q4qx0fWZolv5H1UWYIbRzod003ehXfza/FoI7sB7TVvO0sz",
	"gpSXEo0SCPIE2A997SFXPxZ3YyRzu1hrdRbf2TpLpd00RDFBp4EM96JT/Ctz+gU/+6Vnq+hasTrm/ZoG",
	"DeP2ENiHTF2uHPqukpcrCq720AMUwQVQ0iplpJmYEXqL4AIexVQOuVBw7kglbUwuUWMU8nn8cEIzzMLh",
	"o0eOutcauvxd5v7eIh6X+fVD8hkWytTw1P8FAAD//y5GjF4ffAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
