FROM golang:1.18.5-alpine as build-step
RUN apk add --update --no-cache ca-certificates git

WORKDIR /go/src/github.com/traPtitech/anke-to

RUN go install github.com/cosmtrek/air@v1.27.3

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", "docker/tuning/.air.toml"]
